name: flutcn_ui
description: A UI component library for Flutter inspired by shadcn/ui, providing modular and customizable widgets.
version: 1.1.4
homepage: https://flutcnui.netlify.app/docs
repository: https://github.com/OmarElhassaniAlaoui/flutcn_ui
issue_tracker: https://github.com/OmarElhassaniAlaoui/flutcn_ui/issues
environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  cli_spin: ^1.0.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  http: ^1.3.0
  io: ^1.0.5
  path: ^1.8.0
  prompts: ^2.0.0
dev_dependencies:
  build_runner: ^2.4.6
  lints: ^5.0.0
  test: ^1.24.0
false_secrets:
  - /bin/**

executables:
  flutcn_ui: flutcn_ui
